//Spending Entry Actions
export const GET_SPENDING_ENTRIES = 'GET_SPENDING_ENTRIES';
export const DELETE_SPENDING_ENTRY = 'DELETE_SPENDING_ENTRY';
export const ADD_SPENDING_ENTRY = 'ADD_SPENDING_ENTRY';
export const SPENDING_ENTRIES_LOADING = 'SPENDING_ENTRIES_LOADING';
export const DELETE_ITEM = 'DELETE_ITEM';

//Delete Spending Entry Modal Actions
export const OPEN_DELETE_SPENDING_ENTRY_MODAL = 'OPEN_DELETE_SPENDING_ENTRY_MODAL';
export const CLOSE_DELETE_SPENDING_ENTRY_MODAL = 'CLOSE_DELETE_SPENDING_ENTRY_MODAL';

//Delete Item Modal Actions
export const OPEN_DELETE_ITEM_MODAL = 'OPEN_DELETE_ITEM_MODAL';
export const CLOSE_DELETE_ITEM_MODAL = 'CLOSE_DELETE_ITEM_MODAL';