export const GET_SPENDING_ENTRIES = 'GET_SPENDING_ENTRIES';
export const DELETE_SPENDING_ENTRY = 'DELETE_SPENDING_ENTRY';
export const ADD_SPENDING_ENTRY = 'ADD_SPENDING_ENTRY';
export const SPENDING_ENTRIES_LOADING = 'SPENDING_ENTRIES_LOADING';
export const DELETE_ITEM = 'DELETE_ITEM';